Add support for detecting Realtek network cards
depenguin-me/depenguin-builder pull request #24
Opened 2024-04-26 19:14 UTC by bretton

Add support for detecting Realtek network cards and installing the realtek-re-kmod198 package if detected.

2024-04-26 19:24 UTC, bretton commented
https://github.com/depenguin-me/depenguin-builder/issues/23 and https://github.com/depenguin-me/depenguin-run/issues/79 apply

2024-04-26 20:14 UTC, bretton commented
There is a test image available as follows
```
wget https://depenguin.me/run.sh \
&& chmod +x run.sh \
&& ./run.sh -m https://depenguin.me/files/mfsbsd-14.0-RELEASE-rc1-amd64.iso https://example.org/mypubkey
```

Which server is more likely to have realtek cards? EX44 or new AX42?

2024-04-30 09:03 UTC, grembo requested changes
Isn't this in the wrong place? (I thought INSTALLERCONFIG runs inside qemu, which emulates em0 - so we won't even see the realtek interface).

AFAIK detection should move to the firstboot script that detects network cards.

To do so, I would suggest that we place a copy of the realtek package in a temporary directory and install from there in firstboot as needed.

Something like:

```
pkg fetch realtek-re-kmod198
```

in INSTALLERCONFIG

and then in firstboot (in case we detect the interface)

```
pkg install /path/to/realtek-re-kmod198.pkg
```

2024-04-30 09:03 UTC, grembo commented on customfiles/14_0_INSTALLERCONFIG.sample
> +if_re_count=$(/usr/sbin/pciconf -l | grep "class=0x020000" | grep -c "vendor=0x10ec" | xargs)
when using "grep -c", xargs can be avoided

```
if_re_count=$(/usr/sbin/pciconf -l | grep "class=0x020000" | grep -c "vendor=0x10ec")
```

2024-04-30 10:10 UTC, grembo requested changes
We might even consider to reboot the machine after installing the realtek driver, but maybe that's for a separate iteration.

2024-04-30 10:10 UTC, grembo commented on customfiles/14_0_INSTALLERCONFIG.sample
> +pkg fetch -y realtek-re-kmod198
You can pass "-o /destdir" to `pkg fetch` to make it store fetched packages in /destdir (see `man pkg-fetch`).

2024-04-30 10:10 UTC, grembo commented on customfiles/14_0_INSTALLERCONFIG.sample
> +start_cmd="check_for_realtek | firstboot_depenguin_run | logger -s -t 'depenguin'"
Piping this isn't a good idea (connecting check_for_realtek's standard output to firstboot_depenguin's stdin might cause broken pipe etc.). Best to call `check_for_realtek` from inside `firstboot_depenguin_run`.

2024-04-30 10:13 UTC, grembo requested changes

2024-04-30 10:13 UTC, grembo commented on customfiles/14_0_INSTALLERCONFIG.sample
> +        	sysrc -f /boot/loader.conf hw.re.max_rx_mbuf_sz="2048"
This will not work. sysrc only works with shell compatible variables (like the ones you find in /etc/rc.conf).

```
$ sysrc -f /boot/loader.conf hw.re.max_rx_mbuf_sz="2048"
sysrc: hw.re.max_rx_mbuf_sz: name contains characters not allowed in shell
```

Probably best to fallback to:

```
echo 'hw.re.max_rx_mbuf_sz="2048"' >>/boot/loader.conf
```

2024-04-30 13:29 UTC, bretton commented
test image updated
```
wget https://depenguin.me/run.sh \
&& chmod +x run.sh \
&& ./run.sh -m https://depenguin.me/files/mfsbsd-14.0-RELEASE-rc1-amd64.iso https://example.org/mypubkey
```

2024-04-30 14:57 UTC, grembo approved these changes
This looks reasonably clean to me now. Someone would need to test though :)

2024-04-30 15:12 UTC, bretton commented
> This looks reasonably clean to me now. Someone would need to test though :)

thanks for the fixes @grembo - I'll test on ex44

2024-04-30 16:50 UTC, bretton commented
Something must be wrong with the pkg install from file step?
![Screenshot 2024-04-30 at 18 49 47](https://github.com/depenguin-me/depenguin-builder/assets/4481592/2dfd46fd-7d6c-4a78-8f26-caa6b957d354)

2024-04-30 17:23 UTC, grembo commented
An alternative approach would be to detect the adapter in linux (run.sh) and pass that somehow into the installer.

2024-04-30 17:26 UTC, bretton commented
> An alternative approach would be to detect the adapter in linux (run.sh) and pass that somehow into the installer.

we might have to try that approach, it's not picking up the interface

![Screenshot 2024-04-30 at 19 24 08](https://github.com/depenguin-me/depenguin-builder/assets/4481592/021a05e1-bcda-4b6d-b7e3-b1a28cb3cf85)

2024-04-30 17:42 UTC, bretton commented
from inside rescue
```
lspci -nnvmm | egrep -A6 -B1 '10ec'
Class:	Ethernet controller [0200]
Vendor:	Realtek Semiconductor Co., Ltd. [10ec]
Device:	RTL8125 2.5GbE Controller [8125]
SVendor:	ASUSTeK Computer Inc. [1043]
SDevice:	RTL8125 2.5GbE Controller [87d7]
Rev:	05
ProgIf:	00
```

2024-04-30 18:41 UTC, bretton commented
latest commit works, reboots twice

2024-04-30 21:33 UTC, grembo commented
Hm, this feels really dirty though.

A few problems:
- it should not check for a file to exist to determine if it should install the driver (again), instead a file should be written in the installer and the script should check for it’s absence (pretty much like firstboot). Otherwise deleting that file at any point in the future will lead to an unpleasant surprise for the admin (including running all firstboot things again!)
- re-running firstboot could have weird consequences (as it would re-run other things as well)
- if the firstboot thing stays that way, placing all of that into a separate file would make more sense

Three suggestions (they are alternatives):
1. detect in linux and then already install everything in installerconfig
2. don’t use Linux, but include the pciid check into the firstboot check - so the logic would be: if none of the devices are found, but the Realtek pciid is, install the driver and assume re0 will be found on next boot
3. Install and configure the Realtek driver all the time, remove it if no device is found  

Of these options, 2. sounds like the easiest/most reasonable one. So the logic would be:

- detect all devices (like we always did)
- If none is found (or the one found is named reX), check if there is a Realtek device, based on pciid
- If there was one found, assume it’s re0 and use that in rc.conf, then reboot

This would mean:
- no extra reboots
- No messing with firstboot logic
- Easy to understand (and less probing if a different device was found)

I can help with changing the code, if you want me to.

2024-04-30 22:02 UTC, bretton commented
>     * If there was one found, assume it’s re0 and use that in rc.conf, then reboot

Updated, I'm missing this step however

2024-05-01 13:10 UTC, bretton commented
latest commit is working with ex44, untested on another host yet

2024-05-02 22:18 UTC, grembo commented
Hm, if I read the code correctly, there's an issue:
In case re0 is found (as detected by the non-ports driver), the driver from ports is never installed. In the machines I tested, this became an issue. I think the code needs some restructuring. I will open a PR demonstrating what I mean (that's easier than putting it in clear words atm).

2024-05-02 22:37 UTC, grembo commented
@bretton See #25 (I couldn't test it yet, but sanity checks I did are promising - patch should be quite easy to read 🤞)

2024-05-03 05:26 UTC, bretton commented
> @bretton See #25 (I couldn't test it yet, but sanity checks I did are promising - patch should be quite easy to read 🤞)

awesome thanks @grembo will get to testing later today

2024-05-03 05:26 UTC, bretton commented
closing in favour in #25

2024-05-03 05:26 UTC, closed without merging